### ISSUE TITLE
Bootstrap script for MaxOSX

### ISSUE THREAD

**Issue by JensRantil** [jschauma/jass#13]
Stumbled across this project the other day. Excellent for sharing with non-PGP friends and colleagues. To quickly help them be able to setup `jass` I put together a small bootstrap script here: https://gist.github.com/JensRantil/ba21c50e7720bfc62050 Useful? Maybe link to it from the README?

**Comment by jschauma** [comment]
Thanks! I actually have binary packages that I've now linked to from the main README as well as the quick install instructions similar to what you have in that gist.  Hopefully that'll make it easier for people to get setup.
