### ISSUE TITLE
Re-build OSX dmg with go 1.7+

### ISSUE THREAD

**Issue by mikekap** [jschauma/jass#16]
Golang binaries < 1.7 tend to crash on OSX Sierra. Could we get a new dmg with go 1.7+ with the fix?

**Comment by jschauma** [comment]
I just uploaded https://www.netmeister.org/apps/jass-4.1.1.dmg, which was built using go1.7.4; pgp signature at https://www.netmeister.org/apps/jass-4.1.1.dmg.asc.  Please let me know if that helps fix the problem.

**Comment by mikekap** [comment]
Awesome! Thanks for the quick turnaround and continued maintenance Jan!
