### ISSUE TITLE
Using example GITHUB_URL value routes to a bad address

### ISSUE THREAD

**Issue by toddtimes** [jschauma/jass#19]
In your docs you don't specify that Github will be searched automatically without setting any variables. When using your example GITHUB_URL=https://api.github.com/users/<user>/keys Github fails because you add /<user>.keys to the url.

Using the GITHUB_URL=https://github.com/<user>.keys doesn't work because it doesn't output JSON

Also be wary of adding a trailing / to https://api.github.com/users/<user>/keys

Good: https://api.github.com/users/toddtimes/keys
Fail: https://api.github.com/users/toddtimes/keys/

**Comment by jschauma** [comment]
Fixed via https://github.com/jschauma/jass/commit/9445f4876c319908a60545525a360b05aace3546

Sorry I took forever to take a look here.
