### ISSUE TITLE
Support for GitHib Teams? 

### ISSUE THREAD

**Issue by eduncan911** [jschauma/jass#22]
The docs state that LDAP groups can be used. However, our Enterprise hosted GitHub doesn't allow LDAP connections.  

Maybe something can be done around a call to the Team Membership API?  

https://developer.github.com/v3/teams/members/

Also, specifying a team name instead of a number would be preferable. :)

**Comment by jschauma** [comment]
Eric Duncan <notifications@github.com> wrote:
> The docs state that LDAP groups can be used. However, our Enterprise hosted GitHub doesn't allow LDAP connections.  
> 
> Maybe something can be done around a call to the Team Membership API?  
> 
> https://developer.github.com/v3/teams/members/

I like that idea.  Shouldn't be too difficult to add,
I think.  I'd be happy to accept a PR, but will also
try to take a look at this, although I may not get
around to it until later this month.

-Jan

**Comment by jschauma** [comment]
This should work now.  You can either specify a team by "org/team" name or by numeric id.  Adding the "org" for the team name is necessary since it seems that team names can be non-unique across multiple orgs.  Please give it a try and let me know if you run into any problems.

**Comment by eduncan911** [comment]
And we return to work tomorrow.  Great timing man!  

I would have looked into a PR but was traveling.
