### ISSUE TITLE
GITHUB_URL override not working exactly + Proxies

### ISSUE THREAD

**Issue by eduncan911** [jschauma/jass#23]
Thank you for feature #22 (GitHub Teams)!

I am just now getting to this and running into a few roadblocks.

There seems to be an issue with using `GITHUB_URL` with either the `-u` or `-g` options.  While the overall encryption successfully completes, and gives an encrypted file, it seems to be querying the public internet - which is a violation of our CyberSec policies for things like this (leaking usernames).

```
$ HTTPS_PROXY=http://127.0.0.1:<snip> GITHUB_API_TOKEN=<snip> GITHUB_URL=https://<snip>/api/v3 jass -v -e -g "org/team" -f ~/file.txt > file.txt.enc
=> Checking that all variables look ok...
=> Encrypting...
Unable to GET https://keykeeper.corp.yahoo.com/v2/api/keys?user=<snip-user-1>: Get https://keykeeper.corp.yahoo.com/v2/api/keys?user=<snip-user-1>: Found
Unable to parse json: unexpected end of JSON input
Unable to GET https://keykeeper.corp.yahoo.com/v2/api/keys?user=<snip-user-2>: Get https://keykeeper.corp.yahoo.com/v2/api/keys?user=<snip-user-2>: Found
Unable to parse json: unexpected end of JSON input
Unable to GET https://keykeeper.corp.yahoo.com/v2/api/keys?user=<snip-user-3>: Get https://keykeeper.corp.yahoo.com/v2/api/keys?user=<snip-user-3>: Found
Unable to parse json: unexpected end of JSON input
=> Converting pubkeys to PKCS8 format...
begin-base64 600 message
....<snip>
```

When using the `-u` feature, the same thing happens as well.  Just, for that one user.

So yes, the "Github Teams" feature does work, on a private, internally hosted Github Enterprise, through an HTTPS proxy!!!  It successfully pulls in all the users' pubkeys, and encrypts the file.

However, there are a bunch of these lookups to keykeeper that we need to remove/prevent.

---

On a side note...  I used the public DMG version for macos.  Which, looks like #15 previously raised this as a concern.  I suspecting a different dmg needs to be published?

But with that said, I need to make this scriptable - the auto-install of `jass`, along with its execution across Ubuntu machines (running Jenkins), macOS (for devs), and Windows (for obscure devs).

Would it be safe if I just `git clone` this repo and build it instead for all of these platforms?  Would make provisioning much easier.

**Comment by jschauma** [comment]
Thanks for the report!

I just ripped out support for KeyKeeper completely; to the best of my knowledge it is not used anywhere.  This hopefully addresses that issue.

I also rebuilt the dmg and published it without keykeeper support, but in general, I do think it'd likely be best for you to build your own packages from the repository; the glue in the Makefile should work for macOS; if you add logic for building on Ubuntu or Windows, I'd be glad to merge a PR for that.

I'm going to optimistically close this issue; please do reopen if I messed up and didn't actually resolve it here.

**Comment by eduncan911** [comment]
Thank you and will do!

**Comment by eduncan911** [comment]
So I took a look at the `Makefile`.

Why are you ssh-ing to build the linux_binary and RPM package?

As for Linux, you can use the built in build targets of GO and target each platform.

And for RPM, I'd recommend a docker build environment locally - instead of a remote ssh.  Just seemed very odd to see ssh commands for building in a Makefile.  :)

The only other thing that may get tripped up are the `sed` and `awk` commands.  macOS tends to have their BSD versions of those files not compatible with Linux's GNU versions.  Mostly around escape chars and other params.  

But I'll test it out.

**Comment by jschauma** [comment]
Eric Duncan <notifications@github.com> wrote:
 
> Why are you ssh-ing to build the linux_binary and RPM package?

Because I'm lazy. :-)

I have RH systems accessible that have all the build
tools, but I don't have any local RH containers or
VMs.  So the easiest way for me is to ssh around.

**Comment by eduncan911** [comment]
Have u tried GitHub actions yet?  I've written quite a lot. You can run Windows, Ubuntu, macOS, (and maybe RedHat) all within GitHubs internal CICD, as well as automatically attach to a Release (or even auto tag if tests pass).

Have a gander at a few I've done.  It's completely free, and requires no local build system.

https://github.com/eduncan911/podcast/actions

Click on any to see all the tests and builds that happen.  Here's the code that runs all of that, in a single file:

https://github.com/eduncan911/podcast/blob/master/.github/workflows/go-cicd.yaml

Here's another example of compiling a full operating system and generating a binary to write to disks to boot the machine.  This is a pretty extreme example using a very complicated Makefile:

https://github.com/eduncan911/usbarmory-debian-base_image/actions/runs/44031185

And the code:

https://github.com/eduncan911/usbarmory-debian-base_image/tree/add-release-builds/.github/workflows

You can see the large attachments here, that are automatically added to the release once built:

https://github.com/eduncan911/usbarmory-debian-base_image/releases/tag/20200223

And the best part is it's free.

**Comment by jschauma** [comment]
Thanks, I should look into that!
