### ISSUE TITLE
Is there currently an install that just uses a `curl -O` or `wget` and a `/bin/bash` or /bin/sh` to run?

### ISSUE THREAD

**Issue by jcranston** [jschauma/jass#26]
It would be nice to have a shell-install of this software. Perhaps it already exists? I gave this repo a look and couldn't find one.

I'm a huge fan of Jass and used it when I worked at Twitter. I now use it as my default tool for remote secret sharing.

If this feature doesn't exist, would you be open to a pull request implementing it?

**Comment by jschauma** [comment]
You got it.

```
curl -s https://raw.githubusercontent.com/jschauma/jass/master/src/install.sh | sh
```

This will fetch the binary and manual page and attempt to install it under `${PREFIX}`. If you don't have write access to `${PREFIX}`, add sudo(8) before `sh`.

**Comment by jcranston** [comment]
Fantastic! Thank you so much! This is great, now I can install easily on my Linux machines in the datacenter.

**Comment by jschauma** [comment]
Awesome - glad it's useful for you!
